apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment-service.fullname" . }}
  labels:
   {{- include "payment-service.labels" . | nindent 4 }}
data:
  metrics_exporter: "otlp"
  otel_resource_attributes: "service.name=payment-service"
  otel_otlp_endpoint: "http://jaeger-collector.observability:4318"
  profile: "{{ .Values.profile }}"
