{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "payment-service.fullname" . }}
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /v1/payments
            pathType: Prefix
            backend:
              service:
                name: {{ include "payment-service.fullname" . }}
                port:
                  number: 80
{{- end }}
