spring:
  datasource:
    url: ${JDBC_URL}
    password: ${JDBC_PASS}
    username: ${JDBC_USER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  kafka:
    bootstrap-servers: my-cluster-kafka-brokers.kafka:9092
    consumer:
      group-id: payment-service-group-id
    properties:
      security:
        protocol: none
      sasl:
        jaas:
          config: none
        mechanism: PLAIN
server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  otlp:
    metrics:
      export:
        resource-attributes:
          "service-name" : ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: 'health,info,startup,prometheus'
