spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group-id
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config: ${JAAS_CONFIG}
        mechanism: PLAIN
server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  otlp:
    metrics:
      export:
        resource-attributes:
          "service-name" : ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: 'health,info,startup,prometheus'
